//draw 
draw_set_alpha(image_alpha)
draw_set_color(c_black)
draw_line_width(x_origin-dist,y_origin - 2,x_origin+dist,y_origin - 2, 1)
draw_set_color(c_white)
draw_line_width(x_origin-dist,y_origin,x_origin+dist,y_origin, 1)
draw_self()
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_set_color(c_black)
draw_set_font(global.font_options)
draw_text_outline(x_origin,y_origin-32,"громкость",1,1,c_white,c_black)
draw_text_outline(x_origin,y_origin+32,string(round(audio_get_master_gain(0) * 100))+"%",1,1,c_white,c_black)
draw_set_alpha(1)
